Repository ContainerSolutions/pre-scaling-operator, pull requests merged in 2021-04, with the labels that each got.

#21 New CoC and contributing guide
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/ROADMAP.md
Labels: documentation

#32 Renamed autoscale annotation
  config/random-generator/deployment/random-generator-1.yml
  docs/architecture.md
  internal/resources/deployment.go
  internal/resources/deployment_test.go
  internal/resources/deploymentconfig.go
  internal/resources/deploymentconfig_test.go
Labels: documentation, enhancement

#35 Bugfix/deploymentconfigs e2e
  internal/e2e/deployment_watch_controller_test.go
  internal/e2e/suite_test.go
Labels: bug

#37 Test okd workflow
  .github/workflows/main.yml
  internal/e2e/deployment_watch_controller_test.go
Labels: enhancement

#38 Feature/remove fallback default
  controllers/deploymentConfig_watch_controller.go
  controllers/deployment_watch_controller.go
  internal/e2e/deployment_watch_controller_test.go
  internal/reconciler/reconciler.go
  internal/reconciler/reconciler_test.go
  internal/validations/prefilter.go
Labels: enhancement

#33 Watchers quota check
  config/random-generator/deployment/random-generator-1.yml
  config/random-generator/deployment/random-generator-2.yml
  config/random-generator/deployment/random-generator-3.yml
  config/random-generator/deploymentconfig/random-generator-4.yml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/constants.go
  internal/e2e/deployment_watch_controller_test.go
  internal/e2e/rq_test.go
  internal/quotas/quotas.go
  internal/quotas/quotas_test.go
  internal/reconciler/reconciler.go
  internal/resources/deployment.go
  internal/resources/deployment_test.go
  internal/resources/deploymentconfig.go
  internal/resources/deploymentconfig_test.go
  internal/validations/cluster_validation.go
  pkg/utils/client/client.go
  pkg/utils/math/math.go
  pkg/utils/math/math_test.go
Labels: enhancement

#42 Trying to create first the rq
  internal/e2e/rq_test.go
Labels: bug

#44 Controller e2e tests addition and suite refactor
  internal/e2e/crds_test.go
  internal/e2e/rq_test.go
  internal/e2e/suite_test.go
  internal/e2e/watch_controllers_test.go
Labels: enhancement

#48 Prepare release candidate
  CHANGELOG.md
  CONTRIBUTING.md
  MAINTAINERS.md
  README.md
  RELEASE.md
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clusterscalingstatedefinitions.yaml
  config/crd/patches/cainjection_in_clusterscalingstates.yaml
  config/crd/patches/cainjection_in_scalingstates.yaml
  config/crd/patches/webhook_in_clusterscalingstatedefinitions.yaml
  config/crd/patches/webhook_in_clusterscalingstates.yaml
  config/crd/patches/webhook_in_scalingstates.yaml
  config/default/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/scorecard/bases/config.yaml
  config/scorecard/kustomization.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  docs/architecture.md
  docs/goals.md
  release/getting_started.md
  release/pre-scaling-operator.yaml
Labels: documentation, enhancement

#49 Bugfix/trigger cssd change
  controllers/clusterscalingstatedefinition_controller.go
  internal/e2e/crds_test.go
  internal/e2e/suite_test.go
Labels: bug

#47 Update docker secrets
  .github/workflows/main.yml
  Dockerfile
Labels: enhancement

#50 Events generation
  config/rbac/role.yaml
  controllers/clusterscalingstate_controller.go
  controllers/clusterscalingstatedefinition_controller.go
  controllers/deploymentConfig_watch_controller.go
  controllers/deployment_watch_controller.go
  controllers/scalingstate_controller.go
  internal/e2e/suite_test.go
  internal/reconciler/reconciler.go
  internal/reconciler/reconciler_test.go
  internal/validations/prefilter.go
  main.go
Labels: enhancement, priority
