Repository ContainerSolutions/pre-scaling-operator, pull requests merged in 2021-06, with the labels that each got.

#74 Fixed issue where storage requests would lead to failing Quota check
  internal/quotas/quotas.go
Labels: bug

#75 Moving rate limiting to annotation
  api/v1alpha1/clusterscalingstatedefinition_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scaling.prescale.com_clusterscalingstatedefinitions.yaml
  config/random-generator/deployment/random-generator-1.yml
  config/samples/scaling_v1alpha1_clusterscalingstatedefinition.yaml
  internal/e2e/crds_test.go
  internal/e2e/rq_test.go
  internal/e2e/scaler_test.go
  internal/e2e/suite_test.go
  internal/e2e/watch_controllers_test.go
  internal/resources/common.go
  internal/states/scaling_states.go
Labels: enhancement

#77 Feature/dry run
  api/v1alpha1/clusterscalingstate_types.go
  api/v1alpha1/clusterscalingstatedefinition_types.go
  api/v1alpha1/scalingstate_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/scaling.prescale.com_clusterscalingstatedefinitions.yaml
  config/crd/bases/scaling.prescale.com_clusterscalingstates.yaml
  config/crd/bases/scaling.prescale.com_scalingstates.yaml
  config/random-generator/deployment/random-generator-2.yml
  config/samples/scaling_v1alpha1_clusterscalingstate.yaml
  config/samples/scaling_v1alpha1_clusterscalingstatedefinition.yaml
  config/samples/scaling_v1alpha1_scalingstate.yaml
  controllers/clusterscalingstate_controller.go
  controllers/clusterscalingstatedefinition_controller.go
  controllers/scalingstate_controller.go
  go.mod
  go.sum
  internal/e2e/scaler_test.go
  internal/e2e/suite_test.go
  internal/quotas/quotas.go
  internal/quotas/quotas_test.go
  internal/reconciler/reconciler.go
  internal/reconciler/reconciler_test.go
  internal/resources/common.go
  internal/states/scaling_states.go
Labels: enhancement, priority

#80 [skip ci] Add new docs
  docs/README.md
  docs/architecture/Architecture.png
  docs/architecture/StepScaler.png
  docs/architecture/architecture.md
  docs/developer-guide/developer-guide.md
  docs/ops-guide/ops-guide.md
Labels: enhancement

#81 Fix missing states
  internal/reconciler/reconciler.go
  internal/reconciler/reconciler_test.go
  internal/state_replicas/state_replicas.go
  internal/states/scaling_states.go
Labels: bug

#82 Add better decision making to Namespace Reconcile loop
  .env
  config/manager/manager.yaml
  controllers/clusterscalingstate_controller.go
  controllers/clusterscalingstatedefinition_controller.go
  controllers/deploymentConfig_watch_controller.go
  controllers/deployment_watch_controller.go
  controllers/scalingstate_controller.go
  go.mod
  go.sum
  internal/constants.go
  internal/e2e/scaler_test.go
  internal/e2e/suite_test.go
  internal/quotas/quotas.go
  internal/reconciler/reconciler.go
  internal/reconciler/reconciler_cron.go
  internal/reconciler/reconciler_test.go
  internal/resources/common.go
  internal/resources/common_test.go
  internal/states/scaling_states.go
  internal/states/scaling_states_test.go
  internal/validations/cluster_validation.go
  internal/validations/label_validation.go
  main.go
  pkg/utils/global/concurrrent.go
Labels: enhancement
